services:
  zoo1:
    image: zookeeper
    restart: unless-stopped
    hostname: zoo1
    ports:
      - "2181:2181"
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181
    volumes:
      - zoo1_data:/data
      - zoo1_datalog:/datalog

  zoo2:
    image: zookeeper
    restart: unless-stopped
    hostname: zoo2
    ports:
      - "2182:2181"
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181
    volumes:
      - zoo2_data:/data
      - zoo2_datalog:/datalog

  zoo3:
    image: zookeeper
    restart: unless-stopped
    hostname: zoo3
    ports:
      - "2183:2181"
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181
    volumes:
      - zoo3_data:/data
      - zoo3_datalog:/datalog

  zoonavi:
    image: elkozmon/zoonavigator
    restart: unless-stopped
    ports:
      - "9000:9000"
    depends_on:
      - zoo1
      - zoo2
      - zoo3

  server:
    build: ./server/
    restart: unless-stopped
    ports:
      - "3200:3200"
    environment:
      ZOOKEEPER_ADD: zoo1:2181,zoo2:2181,zoo3:2181
    depends_on:
      - zoonavi

  replicas:
    build: ./server/
    restart: unless-stopped
    environment:
      ZOOKEEPER_ADD: zoo1:2181,zoo2:2181,zoo3:2181
    depends_on:
      - zoonavi

volumes:
  zoo1_data:
  zoo1_datalog:
  zoo2_data:
  zoo2_datalog:
  zoo3_data:
  zoo3_datalog:

